# Site settings
title: Not Enough Hearts
email: jordan.goetze@gmail.com 
description: > # this means to ignore newlines until "baseurl:"
    I'm a software developer with a love for designing web applications (specifically Javascript and Python), reading, listening to music, and playing the classic Zelda and Metroid games.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "jghibiki.github.io" # the base hostname & protocol for your site
github_username:  jghibiki

# Build settings
markdown: kramdown
